
package com.company;


import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class DialogUI extends javax.swing.JFrame {
    Network myNet = new Network();
    /** Creates new form DialogUI */
    int idxIdTable = 0;
    int idxAmountComputers = 1;
    int idxMemoryJTable1 = 2;
    String[] labelsJTable1 = new String [] {
            "Id:", "Кол-во компьютеров:", "Объем памяти"
    };
    String[] labelsJTable2 = new String[] {
            "Инвентарный номер", "Объем памяти"
    };
    public DialogUI() {
        initComponents();

    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jBtnAddNode = new javax.swing.JButton();
        jTxtFieldIdNode = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTxtFieldQueueSize = new javax.swing.JTextField();
        jBtnRmvNode = new javax.swing.JButton();
        jTxtFieldIdComp = new javax.swing.JTextField();
        jTxtFieldMemoryComp = new javax.swing.JTextField();
        jBtnAddComp = new javax.swing.JButton();
        jBtnRmvComp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBtnAddNode.setText("Добавить");
        jBtnAddNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddNodeActionPerformed(evt);
            }
        });

        jTxtFieldIdNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldIdNodeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Id:", "Кол-во компьютеров:", "Объем памяти"
                }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMaxWidth(100);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                        "Инвентарный номер:", "Объем памяти:"
                }
        ));
        jScrollPane4.setViewportView(jTable2);

        jTxtFieldQueueSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldQueueSizeActionPerformed(evt);
            }
        });

        jBtnRmvNode.setText("Удалить");
        jBtnRmvNode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRmvNodeActionPerformed(evt);
            }
        });

        jTxtFieldIdComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldIdCompActionPerformed(evt);
            }
        });

        jTxtFieldMemoryComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFieldMemoryCompActionPerformed(evt);
            }
        });

        jBtnAddComp.setText("Добавить");
        jBtnAddComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAddCompActionPerformed(evt);
            }
        });

        jBtnRmvComp.setText("Удалить");
        jBtnRmvComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRmvCompActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(42, 42, 42)
                                                .addComponent(jScrollPane4))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jBtnAddNode)
                                                                .addGap(54, 54, 54)
                                                                .addComponent(jBtnRmvNode)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jTxtFieldQueueSize, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jTxtFieldIdNode, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel1)
                                                .addGap(118, 118, 118)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jBtnAddComp)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jBtnRmvComp))
                                                        .addComponent(jTxtFieldIdComp, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTxtFieldMemoryComp, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(12, 12, 12)))
                                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jBtnRmvNode)
                                                        .addComponent(jBtnAddNode))
                                                .addGap(36, 36, 36))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTxtFieldIdComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jTxtFieldIdNode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTxtFieldMemoryComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTxtFieldQueueSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(56, 56, 56)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jBtnAddComp)
                                                        .addComponent(jBtnRmvComp))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(126, 126, 126))
        );

        pack();
    }// </editor-fold>


    private void jBtnRmvNodeActionPerformed(java.awt.event.ActionEvent evt) {

        try{
            // находим выделенную строку и извлекаем оттуда id
            int row = jTable1.getSelectedRow();
            if(row == -1){
                throw new Error("Cписок узлов пуст");
            }

            int idSelectedNode = Integer.parseInt(jTable1.getValueAt(row, idxIdTable).toString());
            // находим нужный узел и удаляем компьютера из очереди
            NodeComputers foundNode = myNet.findById(idSelectedNode);
            myNet.removeElement(foundNode);

            // обновляем таблицу
            if(myNet.isEmpty() != true) {
                jTable1.setModel(new DefaultTableModel(
                        myNet.getMainInfo(),
                        labelsJTable1
                ));
                // берем первую строку из таблицы и выводим ее компьютеры
                if(jTable1.getSelectedRow() == -1){
                    jTable1.setRowSelectionInterval(0, 0);
                    int idNewSelectedNode = Integer.parseInt(jTable1.getValueAt(0, 0).toString());
                    NodeComputers foundNewNode = myNet.findById(idNewSelectedNode);
                    jTable2.setModel(new DefaultTableModel(
                            foundNewNode.toStringCircleAtTable(),
                            labelsJTable2
                    ));
                }
            }
            else {
                jTable1.setModel(new DefaultTableModel(
                        new Object [][] {},
                        labelsJTable1
                ));
            }
        }
        catch(Throwable e){
            System.out.println(e);
            String err = String.valueOf(e);
            jLabel1.setText(err);
        }

    }

    private void jBtnAddCompActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            // извлекаем значения из textfield
            int id = Integer.parseInt(jTxtFieldIdComp.getText());
            int memory = Integer.parseInt(jTxtFieldMemoryComp.getText());

            // находим выделенную строку и извлекаем оттуда id
            int row = jTable1.getSelectedRow();
            String idSelectedRowTableString = jTable1.getValueAt(row, 0).toString();
            int idSelectedRowTableInt = Integer.parseInt(idSelectedRowTableString);

            // работаем с данными
            NodeComputers selectedNode = myNet.findById(idSelectedRowTableInt);
            Computer newComp = new Computer(id, memory);
            selectedNode.addElement(newComp);

            // обновляем таблицы:
            // обновляем общее количество в памяти, кол-во компьютеров в первой таблице
            // обновляем таблицу 2
            jTable1.setValueAt(selectedNode.getMemory(), row, idxMemoryJTable1);
            jTable1.setValueAt(selectedNode.getAmountComputers(), row, idxAmountComputers);

            jTable2.setModel(new DefaultTableModel(
                    selectedNode.toStringCircleAtTable(),
                    labelsJTable2
            ));
            jLabel1.setText("");
            // стираем старые значения textfield
//        jTxtFieldIdComp.setText("");
//        jTxtFieldMemoryComp.setText("");
        }
        catch(Throwable e){
            String err = String.valueOf(e);
            jLabel1.setText(err);
        }
    }

    private void jTxtFieldIdNodeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:

    }

    public int getRowByValue(TableModel model, Object value) {
        for (int i = model.getRowCount() - 1; i >= 0; --i) {
            for (int j = model.getColumnCount() - 1; j >= 0; --j) {

                if (model.getValueAt(i, j).equals(value)) {
                    // what if value is not unique?
                    return i;
                }
            }
        }
        return -1;
    }
    public int getRowByValueAndCol(TableModel model, Object value, int idxCol) {
        for (int i = model.getRowCount() - 1; i >= 0; --i) {
            for (int j = model.getColumnCount() - 1; j >= 0; --j) {

                if (model.getValueAt(i, idxCol).equals(value)) {
                    // what if value is not unique?
                    return i;
                }
            }
        }
        return -1;
    }

    private void jBtnAddNodeActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            // извлекаем значения из textfield
            String idString = jTxtFieldIdNode.getText();
            int idInt = Integer.parseInt(idString);
            int queueSize = Integer.parseInt(jTxtFieldQueueSize.getText());

            // работаем с данными: добавляем узел в сеть
            myNet.addElement(new NodeComputers(idInt, queueSize));


            // обновляем таблицы
            jTable1.setModel(new DefaultTableModel(
                    myNet.getMainInfo(),
                    labelsJTable1
            ));

            // выделяем актуальную строку в jTable1
            int idxNewRowSelected = this.getRowByValueAndCol(jTable1.getModel(), idString, idxIdTable);
            jTable1.setRowSelectionInterval(idxNewRowSelected,idxNewRowSelected);

            //находим текущий узел и показываем компьюьтеры этого узла
            NodeComputers foundNode = myNet.findById(idInt);
            jTable2.setModel(new DefaultTableModel(
                    foundNode.toStringCircleAtTable(),
                    labelsJTable2
            ));
            jLabel1.setText("");

// стираем старые значения textfield
//        jTxtFieldIdNode.setText("");
//        jTxtFieldQueueSize.setText("");
        }catch(Throwable e){
            String err = String.valueOf(e);
            jLabel1.setText("В сети уже содержится узел с данным id");
        }



    }




    private void jTxtFieldMemoryCompActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {
        // определяем выделенную строку
        int row = jTable1.getSelectedRow();
        // находим нужный узел для того чтобы показать компьютеры в нем
        Object idClickedRowObject = jTable1.getValueAt(row, idxIdTable);
        int idClickedRowInt = Integer.parseInt(idClickedRowObject.toString());
        NodeComputers foundNode = myNet.findById(idClickedRowInt);
        // обновляем таблицу 2
        jTable2.setModel(new DefaultTableModel(
                foundNode.toStringCircleAtTable(),
                labelsJTable2
        ));

    }



    private void jTxtFieldIdCompActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void jBtnRmvCompActionPerformed(java.awt.event.ActionEvent evt) {
        try{
            // находим выделенную строку и извлекаем оттуда id
            int row = jTable1.getSelectedRow();
            String idSelectedRowTableString = jTable1.getValueAt(row, idxIdTable).toString();
            int idSelectedRowTableInt = Integer.parseInt(idSelectedRowTableString);

            // работаем с данными
            NodeComputers foundNode = myNet.findById(idSelectedRowTableInt);
            foundNode.removeElement();


            // обновляем таблицы:
            jTable1.setModel(new DefaultTableModel(
                    myNet.getMainInfo(),
                    labelsJTable1
            ));
            jTable1.setRowSelectionInterval(row, row);

            jTable2.setModel(new DefaultTableModel(
                    foundNode.toStringCircleAtTable(),
                    labelsJTable2
            ));
        }
        catch(Throwable e){
            String err = String.valueOf(e);
            jLabel1.setText(err);
        }



    }

    private void jTxtFieldQueueSizeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DialogUI().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify
    private javax.swing.JButton jBtnAddComp;
    private javax.swing.JButton jBtnAddNode;
    private javax.swing.JButton jBtnRmvComp;
    private javax.swing.JButton jBtnRmvNode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTxtFieldIdComp;
    private javax.swing.JTextField jTxtFieldIdNode;
    private javax.swing.JTextField jTxtFieldMemoryComp;
    private javax.swing.JTextField jTxtFieldQueueSize;
    // End of variables declaration
//   jButton1.addActionListener(new ActionListener(){
//          public void actionPerformed(ActionEvent ae){
//      String getValue = jTextField1.getText()
//
//   }
//    })
}
